In [ ]:
# Fundamentos de procesamiento de datos para Data Science
# Implementacion Agente AI

## Nombre del grupo:
## Integrantes:

# Documentación
## Descripción del agente
## Como ejecutarlo

In [ ]:
 Fundamentos de procesamiento de datos para Data Science
 Implementacion Agente AI

## Nombre del grupo:
SmartMálaga
## Integrantes:
Lucía Sevilla
Alejandro Rodriguez
Angel Cañadilla
Sabrina García


# Documentación
Portal de datos abiertos del ayuntamientyo de málaga
## Descripción del agente
El agente recibirá un input del usuario sobre información relacionada a los parkings públicos de Málaga, 
podrá consultar:
clima, ocupación de parkings públicos, horas mas concurridas, hacer predicción sobre ocupación de un parking a cierta hora cierto día 
## Como ejecutarlo
Se conectará ollama en ssu versión ll|                                                                                                                                                  ama 3

In [10]:
import pandas as pd
import ollama
import requests
from io import StringIO

data_url =  "https://datosabiertos.malaga.eu/api/3/action/datastore_search?resource_id=0dcf7abd-26b4-42c8-af19-4992f1ee60c6" 

response = requests.get(data_url)
if response.status_code == 200:
    data_json = response.json()
    print(data_json)
    if data_json["success"]:
        registros = data_json["result"]["records"]

        # Extraer la info relevante
        parkings = [{"id": r["id"], "plazas_libres": r["libres"]} for r in registros]
        print(parkings)
        df = pd.DataFrame(parkings)
    else:
        raise Exception("Error en la respuesta de la API")
else:
    raise Exception("Error al descargar el dataset")
print(df.head())

{'help': 'https://datosabiertos.malaga.eu/api/3/action/help_show?name=datastore_search', 'success': True, 'result': {'include_total': True, 'resource_id': '0dcf7abd-26b4-42c8-af19-4992f1ee60c6', 'fields': [{'type': 'int', 'id': '_id'}, {'type': 'text', 'id': 'dato'}, {'type': 'int4', 'id': 'libres'}, {'type': 'text', 'id': 'id'}], 'records_format': 'objects', 'records': [{'_id': 1, 'dato': 'OCUPACION', 'libres': 25, 'id': 'AL'}, {'_id': 2, 'dato': 'OCUPACION', 'libres': 3, 'id': 'MA'}, {'_id': 3, 'dato': 'OCUPACION', 'libres': 108, 'id': 'CA'}, {'_id': 4, 'dato': 'OCUPACION', 'libres': 56, 'id': 'PA'}, {'_id': 5, 'dato': 'OCUPACION', 'libres': 474, 'id': 'AN'}, {'_id': 6, 'dato': 'OCUPACION', 'libres': 114, 'id': 'TE'}, {'_id': 7, 'dato': 'OCUPACION', 'libres': 187, 'id': 'CE'}, {'_id': 8, 'dato': 'OCUPACION', 'libres': 294, 'id': 'CY'}, {'_id': 9, 'dato': 'OCUPACION', 'libres': 389, 'id': 'SJ'}, {'_id': 10, 'dato': 'OCUPACION', 'libres': 173, 'id': 'PB'}], '_links': {'start': '/api/3/action/datastore_search?resource_id=0dcf7abd-26b4-42c8-af19-4992f1ee60c6', 'next': '/api/3/action/datastore_search?offset=100&resource_id=0dcf7abd-26b4-42c8-af19-4992f1ee60c6'}, 'total': 10}}
[{'id': 'AL', 'plazas_libres': 25}, {'id': 'MA', 'plazas_libres': 3}, {'id': 'CA', 'plazas_libres': 108}, {'id': 'PA', 'plazas_libres': 56}, {'id': 'AN', 'plazas_libres': 474}, {'id': 'TE', 'plazas_libres': 114}, {'id': 'CE', 'plazas_libres': 187}, {'id': 'CY', 'plazas_libres': 294}, {'id': 'SJ', 'plazas_libres': 389}, {'id': 'PB', 'plazas_libres': 173}]
   id  plazas_libres
0  AL             25
1  MA              3
2  CA            108
3  PA             56
4  AN            474

Al comprobar que está todo en orden procedenos a hacer merge con el dataset que contiene los nombres de los parkings.

In [15]:
catalogo_url = "https://datosabiertos.malaga.eu/recursos/aparcamientos/ocupappublicosmun/catalogo.csv"

# Cargar el catálogo de aparcamientos
catalogo_df = pd.read_csv(catalogo_url, sep=',', encoding='utf-8')

# Asegurar que las columnas 'id' en ambos DataFrames estén limpias y en el mismo formato
catalogo_df

,id,nombre,direccion,latitude,longitude,altitud
0,CE,Cervantes,Calle CervantesMálaga,36.720863,-4.411915,9.531203
1,PA,El Palo,Calle Alonso Carrillo De AlbornozMálaga,36.721035,-4.360719,8.069582
2,AN,Av. de Andalucía,Avenida De Andalucía - Málaga,36.717327,-4.427712,7.358632
3,CA,Camas,Calle Camas - Málaga,36.720207,-4.424498,7.589293
4,AL,Alcazaba,Plaza La AlcazabaMálaga,36.722431,-4.416517,14.149522
5,SJ,San Juan De La Cruz,Compositor Lemberg Ruiz - 29007 Málaga (Málaga),36.717865,-4.433278,8.787301
6,MA,Pz. de la Marina,Plaza De La MarinaMálaga,36.717415,-4.420047,3.109754
7,TE,Tejón y Rodriguez,Calle Tejón Y RodriguezMálaga,36.723599,-4.421482,10.485368
8,CY,Carlos Haya,"Avenida de Santa Rosa de Lima, 4",36.711930,-4.440970,0.000000
9,PB,Pío Baroja,Avenida Pío Baroja - El Palo - Málaga (Málaga),36.721035,-4.360719,8.069582

In [13]:
df

   id  plazas_libres
0  AL             25
1  MA              3
2  CA            108
3  PA             56
4  AN            474
5  TE            114
6  CE            187
7  CY            294
8  SJ            389
9  PB            173

In [16]:
df['id'] = df['id'].str.strip()
catalogo_df['id'] = catalogo_df['id'].str.strip()

# Realizar el join por 'id'
df_final = df.merge(catalogo_df, on='id', how='left')

# Mostrar los primeros resultados
print(df_final.head())

   id  plazas_libres            nombre  \
0  AL             25          Alcazaba
1  MA              3  Pz. de la Marina
2  CA            108             Camas
3  PA             56           El Palo
4  AN            474  Av. de Andalucía

                                 direccion   latitude  longitude    altitud
0                  Plaza La AlcazabaMálaga  36.722431  -4.416517  14.149522
1                 Plaza De La MarinaMálaga  36.717415  -4.420047   3.109754
2                    Calle Camas -  Málaga  36.720207  -4.424498   7.589293
3  Calle Alonso Carrillo De AlbornozMálaga  36.721035  -4.360719   8.069582
4           Avenida De Andalucía -  Málaga  36.717327  -4.427712   7.358632